apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseName}}-service
spec:
  selector:
    app.kubernetes.io/instance: mongodb
  ports:
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.port}}
