
{{- if .Values.secret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseName}}-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end}}
