apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-service
  labels:
    app.kubernetes.io/name: {{ .Values.deploymentName }}        # Added labels
    app.kubernetes.io/instance: {{ .Values.deploymentName}}    # Added labels
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.deploymentName }}
    app.kubernetes.io/instance: {{ .Values.deploymentName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http   # Added port name to match ServiceMonitor endpoint
