apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deploymentName }}-ingress
spec:
  ingressClassName: nginx
  rules:     

  -  http:
      paths:
      - pathType: Prefix
        path: "/"    
        backend:
          service:
            name: {{ .Values.deploymentName }}-service
            port: 
              number: {{ .Values.service.port}}


     





