apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app.kubernetes.io/instance: {{ .Values.deploymentName }}
    app.kubernetes.io/name: {{ .Values.deploymentName }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: {{ .Values.deploymentName }}
    app.kubernetes.io/name: {{ .Values.deploymentName }}  
    
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    name: http


