{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  # Use a dynamic name to avoid conflicts
  name: {{ .Values.deploymentName }}-dashboard
  # Don't hardcode the namespace!
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
    app: {{ .Values.deploymentName }}
data:
  # This reads the file from the dashboards folder and indents it correctly
  application-dashboard.json: |
{{ .Files.Get "dashboards/application-dashboard.json" | indent 4 }}
{{- end }}