apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-service
spec:
  selector:
    app.kubernetes.io/instance: {{ .Values.deploymentName }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}