
{{ if .Values.serviceMonitor}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.deploymentName}}

  labels:
    release: prometheus # matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.deploymentName }}        # Must match Service labels
      app.kubernetes.io/instance: {{ .Values.deploymentName }} 
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path}}
    interval: 15s
    scrapeTimeout: 10s
{{- end}}
