
{{ if .Values.serviceMonitor}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.deploymentName}}-monitor
  namespace: monitoring
  labels:
    release: prometheus # matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app:  {{ .Values.deploymentName}}
  endpoints:
  - port: web
    path: {{ .Values.serviceMonitor.path}}
    interval: 15s
{{- end}}
