apiVersion: v2
name: frontend-application
description: A Helm chart for deploying the Grade Submission Portal, a frontend service for managing student grade submissions in a Kubernetes environment.
version: 1.0.0